### ISSUE TITLE
Add EULA

### ISSUE THREAD

**Issue by tomdoeslinux** [tomdoeslinux/PixaPencil#276]
Add an EULA to maintain control over the distribution and usage of the software.

**Comment by licaon-kter** [comment]
Interesting.

So we'll have to stop distributing newer versions on F-Droid :(

ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3180

**Comment by jugendhacker** [comment]
So this EULA basically makes this project non free software and rather just "source available" :(

**Comment by tomdoeslinux** [comment]
> So this EULA basically makes this project non free software and rather just "source available" :(

There is no EULA for the original Android-native project, only for the upcoming cross-platform version of the app.

**Comment by jugendhacker** [comment]
But the "original Android-native project" will not be developed any further in favour of the cross platform version (with EULA) right?

Yeah, there is no way F-Droid will publish "source available" software in the repo, in fact the EULA in it's current state even explicitly forbids distributing the app, so not even a third party F-Droid repo with less stricter rules will be able to publish the app.
